import json

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv

load_dotenv()


class CreditMemoGenerator:

    def __init__(self):

        self.llm = ChatGoogleGenerativeAI(
            model="gemini-3.6-flash",
            temperature=0.2
        )

        self.prompt = ChatPromptTemplate.from_messages([
            (
                "system",
                """
You are a credit risk analyst assisting a financial institution.

Generate a professional credit risk memo using ONLY the information
provided in the Credit Risk Engine Output.

STRICT RULES:

1. Never invent or assume information that is not provided.
2. Never invent a date.
3. Never invent a borrower name, loan amount, occupation, employer,
   location, credit history, or financial information.
4. Never change the Probability of Default.
5. Never change the Decision Threshold.
6. Never change or override the Engine Decision.
7. Positive SHAP values indicate that a feature pushed the model toward
   higher predicted default risk.
8. Negative SHAP values indicate that a feature pushed the model toward
   lower predicted default risk.
9. SHAP values are model contribution values, NOT percentages.
10. Do not claim that a feature caused default.
11. Do not introduce lending policies or regulatory requirements that
    are not present in the supplied information.
12. Do not automatically recommend approval or rejection.
13. Follow the Recommended Next Underwriting Action provided by the
    Policy Engine. Do not invent a different action.
14. Use only the evidence supplied by the credit risk engine.
15. Do not repeat the same information unnecessarily.
16. Clearly distinguish between:
    - model prediction
    - SHAP explanation
    - policy-engine action

Use exactly these sections:

1. Credit Risk Assessment
2. Probability of Default
3. Key Risk Drivers
4. Mitigating Factors
5. Overall Assessment
6. Recommendation

In the Recommendation section, clearly distinguish between:
- the machine learning model's classification
- the recommended next underwriting action

Do not include a memo date unless one is explicitly provided.
"""
            ),
            (
                "human",
                """
The following JSON was generated by the Credit Risk Engine:

{risk_context}

Generate the credit risk memo from this information.
"""
            )
        ])

        self.chain = self.prompt | self.llm

    def generate_memo(self, risk_context: dict) -> str:
        """
        Generate a credit memo from structured risk information.
        """

        try:
            # Convert dictionary to readable JSON
            formatted_context = json.dumps(
                risk_context,
                indent=2
            )

            response = self.chain.invoke({
                "risk_context": formatted_context
            })

            # Gemini/LangChain may return either a string or
            # structured content depending on the API response.
            content = response.content

            if isinstance(content, str):
                return content.strip()

            if isinstance(content, list):
                text_parts = []

                for item in content:
                    if isinstance(item, dict) and "text" in item:
                        text_parts.append(item["text"])

                return "\n".join(text_parts).strip()

            return str(content).strip()

        except Exception as e:
            raise RuntimeError(
                f"Credit memo generation failed: {e}"
            ) from e